version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
     
  build:
    commands:
      #- echo Build started on `date`
      #- echo Building the Docker image...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 164896628937.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t nginx:latest -f nginx.Dockerfile .
      - docker tag nginx:latest 164896628937.dkr.ecr.us-west-2.amazonaws.com/nginx:new
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 164896628937.dkr.ecr.us-west-2.amazonaws.com/nginx:new
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' 164896628937.dkr.ecr.us-west-2.amazonaws.com/nginx:new  > imageDetail.json
artifacts:
  files: 
    - 'image*.json'
    - 'appspec.yml'
    - 'taskdef.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
