version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
     
  build:
    commands:
      #- echo Build started on `date`
      #- echo Building the Docker image...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 164896628937.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t php:latest -f php.Dockerfile .
      - docker tag php:latest 164896628937.dkr.ecr.us-west-2.amazonaws.com/php:new
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 164896628937.dkr.ecr.us-west-2.amazonaws.com/php:new
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' 164896628937.dkr.ecr.us-west-2.amazonaws.com/php:new  > imageDef.json
artifacts:
  files: 
    - 'image*.json'
    - 'appspec1.yml'
    - 'taskdef1.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec1.yml
        - taskdef1.json
    ImageArtifact:
      files:
        - imageDef.json
